### ISSUE TITLE
Support quick assert of error message

### ISSUE THREAD

**Issue by uiosun** [jchook/phpunit-assert-throws#4]
Hi, Why are there no shortcuts for asserting `getMessage()`?

like codeception:

```php
        $this->assertThrowsWithMessage(HttpException::class, 'ErrorMessage', function () {
            Request::api('/person/user-feed', ['feed_type' => 9]);
        });
```

**Comment by jchook** [comment]
Hey @Sun-FreePort thanks for the suggestion!

You can evaluate assert the message like this:

```php
$this->assertThrows(
  HttpException::class, 
  function () {
    Request::api('/person/user-feed', ['feed_type' => 9]);
  },
  function($e){
    $this->assertEquals('ErrorMessage', $e->getMessage());
    // ..other assertions..
  }
);
```

Please feel free to submit a PR for some shorthand functions. 

I would recommend making them optional via a separate trait, since I hope to keep the root API simple until we have ample time to dream up a v2 of the API.

Other options for shorthand:

* Text editor "snippets" or macros feature (e.g. in Atom, Sublime, Vim, etc)
* Writing custom shorthand functions on your own projects base `TestCase` class, e.g.

```php

abstract class MyTestCase extends TestCase
{
  use AssertThrows;

  public function assertThrowsWith($class, $message, $code, $fn, $detail = '') 
  {
    $this->assertThrows($class, $fn, function($e) use ($code, $message, $detail) {
      $this->assertEquals($message, $e->getMessage(), $detail);
      $this->assertEquals($code, $e->getCode(), $detail);
    });
  }
}
```

**Comment by uiosun** [comment]
You are right, simple root is good idea

I want to solve this by submit PR
